-- CCFOLIA ROOM FINDER v1
-- Supabase SQL Editorで、このファイル全体を実行してください。

create table if not exists public.rooms (
  id bigint generated by default as identity primary key,
  title text not null,
  room_url text not null unique,
  system text not null,
  tags text[] not null default '{}',
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  is_public boolean not null default true,
  is_approved boolean not null default true,

  constraint rooms_title_length
    check (char_length(title) between 1 and 100),

  constraint rooms_description_length
    check (
      description is null
      or char_length(description) <= 1000
    ),

  constraint rooms_url_format
    check (
      room_url ~ '^https://ccfolia\.com/rooms/[^/]+$'
    ),

  constraint rooms_system_length
    check (char_length(system) between 1 and 100)
);

create index if not exists rooms_system_idx
  on public.rooms(system);

create index if not exists rooms_created_at_idx
  on public.rooms(created_at desc);

create index if not exists rooms_public_approved_idx
  on public.rooms(is_public, is_approved);

alter table public.rooms enable row level security;

drop policy if exists "Anyone can read public approved rooms"
  on public.rooms;

create policy "Anyone can read public approved rooms"
on public.rooms
for select
to anon
using (
  is_public = true
  and is_approved = true
);

drop policy if exists "Anyone can submit public rooms"
  on public.rooms;

create policy "Anyone can submit public rooms"
on public.rooms
for insert
to anon
with check (
  is_public = true
  and is_approved = true
);

-- 注意：
-- v1では誰でも登録可能にするため、is_approved=true で登録されます。
-- 一般公開後にスパム対策・管理者承認制を導入する場合は、
-- このポリシーと登録処理を変更してください。
--
-- また、service_role key / secret key は絶対に app.js に記載しないでください。
